### ISSUE TITLE
Webbreaker webinspect download not working

### ISSUE THREAD

**Issue by matt-fevold** [target/webbreaker#127]
Webbreaker webinspect download --server test-server --scan_name test-scan

is erring out - below is the redacted stack trace.
```
Version 2.1.0
Logging to files: /Users/zasdf/.webbreaker/log/webbreaker-02-27-2018.log
Using webinspect server: -->http://127.0.0.1<-- for query
  Traceback (most recent call last):
  File "/usr/local/bin/webbreaker", line 9, in <module>
    load_entry_point('webbreaker==2.1.0', 'console_scripts', 'webbreaker')()
  File "/Users/zasdf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zasdf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/zasdf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zasdf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zasdf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zasdf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/asdf/Library/Python/2.7/lib/python/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/zasdf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.12-intel/egg/webbreaker/__main__.py", line 398, in download
TypeError: object of type 'NoneType' has no len()
```

it is an i

**Comment by xolian** [comment]
other webinspect download methods are successfully completing, however the above command's request is not passing and returning any data.

**Comment by xolian** [comment]
added additional help to include full url with protocol and port.
